In [1]:
from main import *

print(test1)
moved_test_1 = np.roll(test1, -1)
print(moved_test_1)

[[0 0 0 0]
 [0 0 1 1]
 [0 1 1 1]
 [0 0 0 1]
 [0 0 0 1]]
[[0 0 0 0]
 [0 1 1 0]
 [1 1 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [2]:
miara_2_1_euclidean = main(moved_test_1, wzorzec1 , euclidean)
print(f'Miara niepodobieństwa 2stronne - (przesunięty znak_testowy1, wzorzec1, euclidean) = {miara_2_1_euclidean}')

Miara niepodobieństwa 2stronne - (przesunięty znak_testowy1, wzorzec1, euclidean) = -10.414213562373096


In [4]:
miara_2_2_euclidean = main(moved_test_1, wzorzec2 , euclidean)
print(f'Miara niepodobieństwa 2stronne - (przesunięty znak_testowy1, wzorzec2, euclidean) = {miara_2_2_euclidean}')

Miara niepodobieństwa 2stronne - (przesunięty znak_testowy1, wzorzec2, euclidean) = -15.414213562373096


In [5]:
miara_2_3_euclidean = main(moved_test_1, wzorzec3, euclidean)
print(f'Miara niepodobieństwa 2stronne - (przesunięty znak_testowy1, wzorzec3, euclidean) = {miara_2_3_euclidean}')

Miara niepodobieństwa 2stronne - (przesunięty znak_testowy1, wzorzec3, euclidean) = -12.414213562373096
